---
- name: E2E | Ensure AWX inventory and sync K8s nodes (no json_query)
  hosts: localhost
  gather_facts: false

  vars:
    # === Job Template의 Extra Vars에서 채우십시오 ===
    # AWX(컨트롤러) 접근
    controller_host: "http://awx-service.awx.svc.cluster.local"
    controller_oauthtoken: ""
    organization_name: "Default"
    inventory_name: "k3s-nodes"

    # K8s API 접근
    k8s_host: "https://kubernetes.default.svc"   # EE가 클러스터 내부일 때 권장
    k8s_token: ""                                 # SA 토큰(유효/올바른 audience)
    k8s_validate_certs: false

    # 동기화 시 호스트에 주입할 기본 접속계정
    awx_node_user: "ubuntu"

  tasks:
    #####################################################################
    # 0) 프리플라이트: 컨트롤러 API 확인
    ####################################
