---
- name: E2E | K8s 라벨→AWX 인벤토리 반영 (상세 로그+직접 PATCH)
  hosts: localhost
  connection: local
  gather_facts: false
  any_errors_fatal: true

  vars:
    # === Job Template의 Extra Vars에서 채우십시오 ===
    # AWX 컨트롤러 접근
    controller_host: "http://awx-service.awx.svc.cluster.local"
    controller_oauthtoken: ""
    organization_name: "Default"
    inventory_name: "k3s-nodes"

    # K8s API 접근
    k8s_host: "https://kubernetes.default.svc"
    k8s_token: ""              # SA 토큰(유효/올바른 audience)
    k8s_validate_certs: false  # 내부 CA 없으면 false

    # 호스트 변수 기본값
    awx_node_user: "ubuntu"

  tasks:
  - block:
      #####################################################################
      # 0) 프리플라이트: AWX API 접근 확인
      #####################################################################
      - name: "[0] Preflight | /api/v2/ping"
        uri:
          url: "{{ controller_host | regex_replace('/$','') }}/api/v2/ping/"
          method: GET
          headers:
            Authorization: "Bearer {{ controller_oauthtoken }}"
